### ISSUE TITLE
Getting draft events via master branch

### ISSUE THREAD

**Issue by sigdestad** [enonic/lib-guillotine#160] opened 2021-05-07 10:53 UTC
Using subscriptions, I'm getting events from draft branch, even when connected to master branch.

![Screenshot 2021-05-07 at 12 50 37](https://user-images.githubusercontent.com/482228/117439448-22fb0080-af33-11eb-9273-a8a96b48fded.png)

**Comment by anatol-sialitski** [comment] 2021-05-07 11:29
@sigdestad Do you use some custom configuration for `subscriptionEventTypes`?

**Comment by anatol-sialitski** [comment] 2021-05-07 12:39
I've reproduce it too. The reason is lib-context returns  the draft branch all time. I will figure out how to fix it.

**Comment by anatol-sialitski** [comment] 2021-05-31 10:35
this bug was fixed in scope https://github.com/enonic/lib-guillotine/issues/166 issue.

**Closed by anatol-sialitski** 2021-05-31 10:35 UTC
Labels: bug
